namespace Azaliq.Data.Models.Models.Enum
{
    public enum CountryCode
    {
        UnitedStates = 1,
        UnitedKingdom = 44,
        Germany = 49,
        France = 33,
        Canada = 1,
        Australia = 61,
        India = 91,
        Brazil = 55,
        Japan = 81,
        Mexico = 52,
        Russia = 7,
        SouthAfrica = 27,
        China = 86,
        Italy = 39,
        Spain = 34,
        Netherlands = 31,
        Sweden = 46,
        Norway = 47,
        Denmark = 45,
        Finland = 358,
        Belgium = 32,
        Switzerland = 41,
        Austria = 43,
        Ireland = 353,
        NewZealand = 64,
        Argentina = 54,
        Chile = 56,
        Colombia = 57,
        CzechRepublic = 420,
        Greece = 30,
        Hungary = 36,
        Israel = 972,
        Malaysia = 60,
        Bulgaria = 359,
        Nigeria = 234,
        Pakistan = 92,
        Peru = 51,
        Philippines = 63,
        Poland = 48,
        Portugal = 351,
        SaudiArabia = 966,
        Singapore = 65,
        SouthKorea = 82,
        Taiwan = 886,
        Thailand = 66,
        Turkey = 90,
        Ukraine = 380,
        UnitedArabEmirates = 971,
        Vietnam = 84
    }

}
